In [1]:
#2*2 Matrix code

In [1]:
import numpy as np

In [2]:
def det(arr):
    if arr.shape == (2,2):
        return arr[0][0]*arr[1][1] - arr[1][0] * arr[0][1]

In [3]:
def change(arr):
    temp = arr[0][0]
    arr[0][0] = arr[1][1]
    arr[1][1] = temp
    temp = arr[1][0]*-1
    arr[1][0] = arr[0][1]*-1
    arr[0][1] = temp
#     print(mat)

In [7]:
def inv(mat):
    d = det(mat)
#     print(d)
    change(mat)
#     print(mat)
    mat = mat / d
    print(mat)

In [8]:
mat = np.array([[1,2],[3,4]])
print(mat)
inv(mat)

[[1 2]
 [3 4]]
[[-2.   1.5]
 [ 1.  -0.5]]


In [8]:
#3*3 Matrix code

In [9]:
def det3D(mat):
    if mat.shape == (3,3):
        a1 = mat[0][0]*(mat[1][1]*mat[2][2] - mat[1][2]*mat[2][1])
        a2 = mat[0][1]*(mat[1][0]*mat[2][2] - mat[2][0]*mat[1][2])
        a3 = mat[0][2]*(mat[1][0]*mat[2][1] - mat[2][0]*mat[1][1])
        det = a1+a3-a2
        return det

In [10]:
def isInv(mat):
    return det3D(mat)!= 0

In [11]:
def trans(mat):
    return mat.T

In [12]:
def minors(mat):
    a00 = mat[1][1]*mat[2][2] - mat[1][2]*mat[2][1]
    a01 = mat[1][0]*mat[2][2] - mat[2][0]*mat[1][2]
    a02 = mat[1][0]*mat[2][1] - mat[2][0]*mat[1][1]
    
    a10 = mat[0][1]*mat[2][2] - mat[0][2]*mat[2][1]
    a11 = mat[0][0]*mat[2][2] - mat[0][2]*mat[2][0]
    a12 = mat[0][0]*mat[2][1] - mat[2][0]*mat[1][1]
    
    a20 = mat[0][1]*mat[1][2] - mat[1][1]*mat[1][2]
    a21 = mat[0][0]*mat[1][2] - mat[1][0]*mat[0][2]
    a22 = mat[0][0]*mat[1][1] - mat[1][0]*mat[0][1]
    result = np.array([[a00,a01,a02],[a10,a11,a12],[a20,a21,a22]])
    return result

In [13]:
def cofactors(mat):
    mat[0][1] = -1*mat[0][1]
    mat[1][0] = -1*mat[1][0]
    mat[1][2] = -1*mat[1][2]
    mat[2][1] = -1*mat[2][1]

In [14]:
mat = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(mat)
if isInv(mat):
    det = det3D(mat)
    m = minors(mat)
    cofactors(m)
    inv = m / det
    print(inv)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]
[[ 2.375 -1.625  0.125]
 [-1.625  1.375 -0.625]
 [ 0.25  -0.375 -0.125]]
